dolla = float(input("Enter amount to take charge for: "))

print("Your change is: ")

twenties = int(dolla // 20)
ten = int((dolla % 20) // 10)
fives = int(((dolla % 20) % 10)//5)
ones = int(((dolla % 20) % 10) // 1)
quarter = int((((dolla % 20) % 10) % 1) // 0.25)
dime = int(((((dolla % 20) % 10) % 1) % 0.25) // 0.1)
nickel = int((((((dolla % 20) % 10) % 1) % 0.25) % 0.1) // 0.05)
penny = int(((((((dolla % 20) % 10) % 1) % 0.25) % 0.1) % 0.05)//0.01)

print(f'{twenties} twenties')
print(f'{ten} ten')
print(f'{fives} five')
print(f'{ones} ones')
print(f'{quarter} quarters')
print(f'{dime} dimes')
print(f'{nickel} nickel')
print(f'{penny} penny')
